In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(Y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 4s 4ms/step - loss: 0.5636 - accuracy: 0.7471
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4761 - accuracy: 0.7955
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4522 - accuracy: 0.8002
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4363 - accuracy: 0.8086
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4281 - accuracy: 0.8119
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4213 - accuracy: 0.8136
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4149 - accuracy: 0.8186
Epoch 8/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4093 - accuracy: 0.8209
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4039 - accuracy: 0.8231
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3990 - accura

In [ ]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 1s 5ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1520   75]
 [ 202  203]]


0.8615